export const npcRegistryABI = [
  { type: "event", name: "NPCRegistered", inputs: [{ indexed: true, name: "npcHash", type: "bytes32" }, { indexed: false, name: "npcId", type: "string" }, { indexed: false, name: "name", type: "string" }, { indexed: false, name: "npcType", type: "uint8" }, { indexed: false, name: "timestamp", type: "uint256" }] },
  { type: "function", name: "registerNPC", inputs: [{ name: "npcId", type: "string" }, { name: "name", type: "string" }, { name: "npcType", type: "uint8" }, { name: "initialCredits", type: "uint256" }, { name: "initialPriceModifier", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "getNPC", inputs: [{ name: "npcId", type: "string" }], outputs: [{ name: "npcId", type: "string" }, { name: "name", type: "string" }, { name: "npcType", type: "uint8" }, { name: "credits", type: "uint256" }, { name: "priceModifier", type: "uint256" }, { name: "reputation", type: "int256" }, { name: "isActive", type: "bool" }, { name: "lastAction", type: "uint256" }, { name: "lastHeartbeat", type: "uint256" }, { name: "totalInteractions", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "getNPCInventory", inputs: [{ name: "npcId", type: "string" }], outputs: [{ components: [{ name: "itemId", type: "string" }, { name: "itemName", type: "string" }, { name: "itemType", type: "string" }, { name: "quantity", type: "uint256" }], name: "", type: "tuple[]" }], stateMutability: "view" },
  { type: "function", name: "getNPCCount", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "heartbeat", inputs: [{ name: "npcId", type: "string" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updateCredits", inputs: [{ name: "npcId", type: "string" }, { name: "newCredits", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "updateReputation", inputs: [{ name: "npcId", type: "string" }, { name: "delta", type: "int256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "addInventory", inputs: [{ name: "npcId", type: "string" }, { name: "itemId", type: "string" }, { name: "itemName", type: "string" }, { name: "itemType", type: "string" }, { name: "quantity", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "removeInventory", inputs: [{ name: "npcId", type: "string" }, { name: "itemId", type: "string" }, { name: "quantity", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
] as const;
